server:
  port: ${GATEAWAY_PORT:8082}

spring:
  application:
    name: api-gateway

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/foodapp}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: foodapp
              uri: http://${FOODAPP_BACKEND:localhost}:8081
              predicates:
                - Path=/api/foodapp/**
              filters:
                - RewritePath=/api/foodapp/(?<segment>.*), /api/${segment}
            - id: tradeapp
              uri: http://${TRADEAPP_BACKEND:localhost}:8000
              predicates:
                - Path=/api/tradeapp/**
              filters:
                - RewritePath=/api/tradeapp/(?<segment>.*), /api/${segment}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO

token:
  signing:
    key: ${SIGN_KEY:mySecretSigningKey195456756012345346218234567890}

cors:
  allowed-origins: http://localhost:*, https://*.kushy.dev, http://*.kushy.dev